server:
  port: 2020

spring:
  application:
    name: StockItemRequestJSC
  profiles:
    active: prod


  datasource:
    url: jdbc:mysql://localhost:3306/inventory#change this to your database url
    password: caroline_654321 #change this to your database username

    username: root #change this to your database password
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect


        spring:
          rabbitmq:
            host: localhost
            port:   15672
            username: guest
            password: guest



  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rappidmq:
  queue:
    name: javaguides
rabbitmq:
  exchange:
    name: javaguides_name

    rabbitmq:
      routing:
        key: javaguides_routing